app/models.py
import os
import sys

file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)

from app import db
from whoosh.analysis import StemmingAnalyzer
import flask_whooshalchemy as whooshalchemy

class Dream(db.Model):
    
    __tablename__ = 'dreams'
    __searchable__ = ['name', 'description']
    __analyzer__ = StemmingAnalyzer()
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    description = db.Column(db.String)
    
    def __repr__(self):
        return '<Dream %r>' %self.name

app/main/forms.py
import os
import sys

file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired 
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, FileField, validators
from wtforms.validators import Required, Length, Email, Regexp, EqualTo


class SearchForm(FlaskForm):
    search = StringField("Type in your dream", validators = [Required(message='Please type in what would you like to find')])
    submit = SubmitField("Submit")
    
class AddForm(FlaskForm):
    name = StringField("Add a dream title")
    description = TextAreaField("Add a dream", validators=[Required()])
    submit = SubmitField('Send')

app/__init__.py
import os
import sys

file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
import flask_whooshalchemy as whooshalchemy
from whoosh.analysis import StemmingAnalyzer
from config import config

boostrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    db.init_app(app)
    boostrap.init_app(app)
    
    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    #add here other blueprints to run
    return app

app/main/__init__.py
import os
import sys

file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
import os
import sys

file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)

from . import main
from forms import SearchForm, AddForm
from app import db
from app.models import Dream
from flask import Flask, request, make_response, redirect, abort, render_template, url_for, flash, current_app

@main.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()
    # if form.validate_on_submit():
    #     results = Dream.query.whoosh_search(form.search.data).all()
    #     if len(results)>1:
    #         return redirect(url_for('main.results',dream=form.search.data))
    #     elif len(results)==1:
    #         id=results[0].id
    #         return redirect(url_for('main.dream',id=id))
    #     else:
    #         return render_template('notfound.html', form=form)
    return render_template('index.html', form=form)
    
@main.route('/dream/<int:id>', methods=['GET','POST'])
def dream(id):
    form=SearchForm()
    dream = Dream.query.filter_by(id=id).first()
    """Creating a link to other dream """
    if '[' in dream.description:
        _to = dream.description.index('[')
        _from = dream.description.index(']')
        link_dream  =  Dream.query.filter_by(name = dream.description[_from+6:-1]).first()
        if link_dream is not None:
            name = dream.name
            description = dream.description[:_to]
            return render_template('dream.html',dream=dream,form=form, link_dream=link_dream, 
                                    name = name, description = description
                                    )
        # else:
        #     pointed = dream.description[_from+6:-1]
        #     return redirect(url_for('main.results', dream=pointed))
        else:
            name = dream.name
            description = dream.description[:_to]
            return render_template('dream.html',dream=dream,form=form, link_dream=link_dream, 
                                    name = name, description = description
                                    )
    else:
        return render_template('dream.html',dream=dream,form=form)
    
@main.route('/search', methods=['GET','POST'])
def search():
    form=SearchForm()
    name=request.form['search']
    results = Dream.query.whoosh_search(name).all()
    if len(results)>1:
            return render_template('results.html', results=results,form=form)
    elif len(results)==1:
        id=results[0].id
        return redirect(url_for('main.dream',id=id))
    else:
        flash('No dreams found, sorry :(')
        return render_template('notfound.html', form=form)

@main.route('/results/<dream>', methods=['GET', 'POST'])
def results(dream):
    form = SearchForm()
    results = Dream.query.whoosh_search(dream).all()
    return render_template('results.html', results=results, form=form)
    

@main.route('/add', methods=['GET','POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        dream = Dream(name = form.name.data, description = form.description.data)
        db.session.add(dream)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('add.html', form=form)


# @main.route('/add_all', methods = ['GET', 'POST'])
# def add_all():
    
#     import xml.etree.ElementTree as ET
#     from collections import OrderedDict as OrD
#     tree = ET.parse(current_app.config['XML_DREAMS'])
#     root = tree.getroot()
#     dreams = OrD() #ordered dictionary for getting last key added
#     to_database = {}
    
#     for page in root.findall('page'):

#     	if int(page.attrib['number']) > 33 and (int(page.attrib['number']))<394 : 
#     		for text in page:
#     			if int(text.attrib['font']) == 0: 				#font for description
#     				last_key=list(dreams.items())[-1][0]		#geting last key from dictionary
#     				dreams[last_key].append(text.text)			#and adding value to it
    
#     			elif int(text.attrib['font']) == 6: 			#font for dream
#     				for dream in text:							
#     					dreams[dream.text] = []					#addding new key - dream, to the dreams
    


#     for k,v in dreams.items():                                  #adding from ordered dictionary to unordered
#     	to_database[k] = str(' '.join(v))
#     try:
#         for k, v in to_database.items():
#             dream = Dream(name = k, description = v)
#             db.session.add(dream)
#             db.session.commit()
#         return redirect(url_for('main.index'))
#     except:
#         return "Oops something went wrong"

app/templates/add.html
{%extends "base.html"%}

{%block page_content%}
<div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
          {{wtf.quick_form(form)}}
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>
{%endblock%}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block head %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dreamopedia</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/fonts/font-awesome.min.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abel">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Article-Clean.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Footer-Basic.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Footer-Clean.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Footer-Dark.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Good-login-dropdown-menu.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Good-login-dropdown-menu1.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Login-Form-Dark.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Navigation-Clean.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/styles.css') }}">
  
</head>
{% endblock %}
{% block title %}My App{% endblock %}
{% block body %}
<body style="font-family:Abel, sans-serif;">
    <div class="article-clean">
        <div class="container col-12" id="container-top">
            {% block navbar %}
            <nav class="navbar navbar-light navbar-expand-md d-block navigation-clean" id="nav-main" style="background-color:rgba(29,181,214,0);font-family:Roboto, sans-serif;">
                <div class="container"><a class="navbar-brand" href="{{url_for('main.index')}}" data-bs-hover-animate="rubberBand" style="color:#ffffff;font-weight:normal;font-style:normal;background-repeat:no-repeat;background-image:url({{ url_for('static', filename='assets/img/dreamopedia_logo.png') }});background-size:contain;background-position:center;font-size:40px;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</a>
                    <button
                        class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navcol-1">
                            <ul class="nav navbar-nav ml-auto"></ul>
                            <ul class="nav navbar-nav"></ul>
                            <ul class="nav navbar-nav">
                                <li class="nav-item" role="presentation"><a class="nav-link" href="#" style="color:rgb(255,255,255);">Start</a></li>
                            </ul>
                        </div>
                </div>
            </nav>
            <div class="row">
                <div class="col-10 col-sm-11 col-md-11 col-xl-11 col-12 col-xl-12 col-md-12 col-sm-12" style="width:100%;padding-right:0px;padding-left:0px;">
				<form action="{{ url_for('main.search') }}" method=post>
				<input class="form-control-lg float-left" name="search" type="search" style="margin-top:10px;margin-bottom:10px;padding-right:16px;margin-left:12%;width:70%;font-family:Roboto, sans-serif;border:none;" placeholder="What have you dreamed about">
				<button name=submit class="btn btn-primary btn-lg float-left"
                        type="button" data-bs-hover-animate="pulse" style="margin-top:10px;margin-bottom:10px;padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:0px;background-color:#03366B;/*box-shadow:0 0 0 .2rem #03366B;*/border-color:white;max-width:46px;max-height:46px;height:90%;width:90%;margin-left:10px;"><i class="fa fa-search"></i></button></div>
				</form>
			</div>
        {% endblock %}
        </div>
    </div>
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-12"></div>
            </div>
            <div class="row">
                <div class="col-md-4 col-xl-2 col-md-2 col-lg-2"></div>
                <div class="col-md-4 col-xl-8 col-md-4 col-lg-8" style="padding-top:15px;padding-bottom:15px;font-family:Roboto, sans-serif;">
					{% block page_content %} {% endblock %}
                </div>
                <div class="col-md-4 col-xl-2 col-md-2 col-lg-2"></div>
            </div>
        </div>
    {% endblock %}
    <div class="d-block" id="container-search" style="background-color:rgb(29,181,214);width:100%;"></div>
    <div class="footer-basic col-12">
        <footer>
            <div class="social"></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Dreamopedia © 2018</p>
        </footer>
    </div>
    <div></div>
    <div></div>
    <script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/bs-animation.js') }}"></script>
</body>
{%endblock%}
{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/dream.html
{%extends "base.html"%}

{%block page_content%}
<div class="container">
  <div class="row">
    <div class="col-sm">
    <!--{{wtf.quick_form(form,url_for('main.search'))}}-->
    <br><br><br><hr>
    {% if link_dream %}
      {{name}}<br>
      {{description}}<br>
      
      <p>See: <a href='{{url_for('main.dream', id=link_dream.id)}}'>{{link_dream.name}}<br></p>
    {%else%}
      <h1>{{dream.name}}</h1><br>
      <p>{{dream.description}}</p>
    {%endif%}
    </div>
  </div>
</div>
{%endblock%}

app/templates/index.html
{%extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}

{%block page_content%}
  <div class="container">
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
    <!--{{wtf.quick_form(form)}}-->
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>
{%endblock%}
<h1>test</h1>

app/templates/notfound.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<h1>Dream not found :(</h1>
<!--{{wtf.quick_form(form,url_for('main.search'))}}-->
{%endblock%}

app/templates/results.html
{%extends "base.html"%}
{% import "bootstrap/wtf.html" as wtf %}

{%block page_content%}
<!--{{wtf.quick_form(form,url_for('main.search'))}}-->
    
    {%for result in results%}
        <a href='{{url_for('main.dream', id=result.id)}}'>{{result.name}}<br>
    {%endfor%}
{%endblock%}